spring.application.name=identity-service

# Importation depuis le Config Server
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.fail-fast=false
spring.cloud.config.import-check.enabled=false

server.port=${identity-service.port}

spring.cloud.config.profile=dev

#BD
spring.datasource.url=${identity-service.datasource-url}
spring.datasource.username=${identity-service.username}
spring.datasource.password=${identity-service.password}

#JPA
spring.jpa.hibernate.ddl-auto=${identity-service.hibernate-ddl-auto}
spring.jpa.show-sql=${identity-service.show-sql}

#eureka
eureka.client.service-url.defaultZone=${identity-service.urlregistry}

# JWT
jwt.secret=${identity-service.jwt-secret}
jwt.expiration=${identity-service.jwt-expiration}

# MAIL
spring.mail.host=${identity-service.mail-host}
spring.mail.port=${identity-service.mail-port}
spring.mail.username=${identity-service.mail-username}
spring.mail.password=${identity-service.mail-password}